//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------- Function Prototypes --------------------

int32_t do_stuff(void);
int32_t function_80483d0(int32_t a1, int32_t a2);
int32_t function_80483e0(int32_t a1);
int32_t function_80483f0(int32_t a1, int32_t a2, int32_t a3);
int32_t function_8048400(void);
int32_t function_8048410(int32_t a1);
int32_t function_8048420(int32_t a1);
int32_t function_8048430(int32_t a1, int32_t a2);

// --------------------- Global Variables ---------------------

int32_t g1 = 0;

// ------------------------ Functions -------------------------

// Address range: 0x80483d0 - 0x80483d6
int32_t function_80483d0(int32_t a1, int32_t a2) {
    // 0x80483d0
    return strcmp();
}

// Address range: 0x80483e0 - 0x80483e6
int32_t function_80483e0(int32_t a1) {
    // 0x80483e0
    return printf();
}

// Address range: 0x80483f0 - 0x80483f6
int32_t function_80483f0(int32_t a1, int32_t a2, int32_t a3) {
    // 0x80483f0
    return fgets();
}

// Address range: 0x8048400 - 0x8048406
int32_t function_8048400(void) {
    // 0x8048400
    return geteuid();
}

// Address range: 0x8048410 - 0x8048416
int32_t function_8048410(int32_t a1) {
    // 0x8048410
    return puts();
}

// Address range: 0x8048420 - 0x8048426
int32_t function_8048420(int32_t a1) {
    // 0x8048420
    return system();
}

// Address range: 0x8048430 - 0x8048436
int32_t function_8048430(int32_t a1, int32_t a2) {
    // 0x8048430
    return setreuid();
}

// From module:   /root/gamefiles/leviathan/levels/leviathan3/level3.c
// Address range: 0x804855b - 0x8048618
// Line range:    7 - 21
int32_t do_stuff(void) {
    int32_t v1 = 0x706c6e73; // bp-279
    int32_t v2; // bp-268
    int32_t v3 = &v2; // 0x8048597
    function_80483f0(v3, 256, g1);
    if (function_80483d0(v3, (int32_t)&v1) != 0) {
        // 0x80485fe
        function_8048410((int32_t)"bzzzzzzzzap. WRONG");
        // branch -> 0x804860e
    } else {
        // 0x80485c3
        function_8048410((int32_t)"[You've got shell]!");
        int32_t v4 = function_8048400(); // 0x80485d3
        function_8048430(function_8048400(), v4);
        function_8048420((int32_t)"/bin/sh");
        // branch -> 0x804860e
    }
    // 0x804860e
    return 0;
}

// From module:   /root/gamefiles/leviathan/levels/leviathan3/level3.c
// Address range: 0x8048618 - 0x80486c4
// Line range:    24 - 42
int main(int argc, char ** argv) {
    char kaka[7]; // bp-51
    char morenothing[7]; // bp-44
    // 0x8048618
    morenothing = {104, 0, 0, 0, 0, 0, 0};
    kaka = {107, 0, 0, 0, 0, 0, 0};
    function_80483d0((int32_t)&morenothing, (int32_t)&kaka);
    function_80483e0((int32_t)"Enter the password> ");
    do_stuff();
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// int32_t fgets(void);
// int32_t geteuid(void);
// int32_t printf(void);
// int32_t puts(void);
// int32_t setreuid(void);
// int32_t strcmp(void);
// int32_t system(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (6.3.0)
// Detected language: C
// Detected functions: 9
// Decompilation date: 2019-12-25 12:50:24
