//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------- Function Prototypes --------------------

int32_t function_80483b0(int32_t a1, int32_t a2);
int32_t function_80483c0(int32_t a1);
int32_t function_80483d0(int32_t a1);
int32_t function_80483e0(void);
int32_t function_80483f0(int32_t a1);
int32_t function_8048400(int32_t a1);
int32_t function_8048410(int32_t a1, int32_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x80483b0 - 0x80483b6
int32_t function_80483b0(int32_t a1, int32_t a2) {
    // 0x80483b0
    return strcmp();
}

// Address range: 0x80483c0 - 0x80483c6
int32_t function_80483c0(int32_t a1) {
    // 0x80483c0
    return printf();
}

// Address range: 0x80483d0 - 0x80483d6
int32_t function_80483d0(int32_t a1) {
    // 0x80483d0
    return getchar();
}

// Address range: 0x80483e0 - 0x80483e6
int32_t function_80483e0(void) {
    // 0x80483e0
    return geteuid();
}

// Address range: 0x80483f0 - 0x80483f6
int32_t function_80483f0(int32_t a1) {
    // 0x80483f0
    return puts();
}

// Address range: 0x8048400 - 0x8048406
int32_t function_8048400(int32_t a1) {
    // 0x8048400
    return system();
}

// Address range: 0x8048410 - 0x8048416
int32_t function_8048410(int32_t a1, int32_t a2) {
    // 0x8048410
    return setreuid();
}

// Address range: 0x804853b - 0x8048604
int main(int argc, char ** argv) {
    int32_t v1 = 0x786573; // bp-24
    function_80483c0((int32_t)"password: ");
    int32_t v2 = function_80483d0((int32_t)"password: "); // 0x8048587
    char v3 = v2; // bp-20
    function_80483d0(0x1000000 * function_80483d0(0x1000000 * v2 / 0x1000000) / 0x1000000);
    int32_t v4 = function_80483b0((int32_t)&v3, (int32_t)&v1); // 0x80485ae
    if (v4 != 0) {
        // 0x80485e5
        function_80483f0((int32_t)"Wrong password, Good Bye ...");
        // branch -> 0x80485f5
    } else {
        int32_t v5 = function_80483e0(); // 0x80485ba
        function_8048410(function_80483e0(), v5);
        function_8048400((int32_t)"/bin/sh");
        // branch -> 0x80485f5
    }
    // 0x80485f5
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// int32_t getchar(void);
// int32_t geteuid(void);
// int32_t printf(void);
// int32_t puts(void);
// int32_t setreuid(void);
// int32_t strcmp(void);
// int32_t system(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (6.3.0)
// Detected functions: 8
// Decompilation date: 2019-12-22 15:52:06
